name: Run CI checks

on: [pull_request]

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Verify PR
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: npm run nx affected -- --target=build --base=origin/master --parallel
      - run: npm run nx affected -- --target=test --base=origin/master --parallel
      - run: npm run nx affected -- --target=lint --base=origin/master --parallel
      - run: npm run nx affected -- --target=e2e --base=origin/master --parallel
      - run: npx @nrwl/nx-cloud stop-all-agents
  agent1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: npx @nrwl/nx-cloud start-agent
  agent2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: npx @nrwl/nx-cloud start-agent
  agent3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: npx @nrwl/nx-cloud start-agent
  agent4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: npx @nrwl/nx-cloud start-agent
  agent5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: npx @nrwl/nx-cloud start-agent
